name: Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 代码迁出
        uses: actions/checkout@v4

      - name: 构建Java环境
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: 设置缓存
        uses: gradle/actions/setup-gradle@v3

      - name: 解码生成 jks
        run: echo $KEYSTORE_BASE64 | base64 -di > keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: 生成apk
        run: chmod +x ./gradlew && ./gradlew assembleRelease

        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD}}

      - name: 获取版本号
        id: version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          echo "version=$TIMESTAMP-$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "tag=v$TIMESTAMP-$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: 重命名应用
        run: |
          for file in tv/build/outputs/apk/release/app-*.apk; do
            if [[ $file =~ app-(.?*)release.apk ]]; then
              new_file_name="tv/build/outputs/apk/release/mytv-android-${BASH_REMATCH[1]}${{ steps.version.outputs.version }}.apk"
              mv "$file" "$new_file_name"
            fi
          done

      - name: Prepare artifacts
        run: |
          mkdir artifacts
          cp tv/build/outputs/apk/release/*.apk artifacts/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          # Artifact name
          name: ${{ steps.version.outputs.version }}
          # A file, directory or wildcard pattern that describes what to upload
          path: artifacts/*
          # The desired behavior if no files are found using the provided path.

          
